/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package app-0.1.0.0 */
#ifndef VERSION_app
#define VERSION_app "0.1.0.0"
#endif /* VERSION_app */
#ifndef MIN_VERSION_app
#define MIN_VERSION_app(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_app */

/* package base-4.8.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.8.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  8 || \
  (major1) == 4 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package miso-0.12.0.0 */
#ifndef VERSION_miso
#define VERSION_miso "0.12.0.0"
#endif /* VERSION_miso */
#ifndef MIN_VERSION_miso
#define MIN_VERSION_miso(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_miso */

/* package aeson-0.9.0.1 */
#ifndef VERSION_aeson
#define VERSION_aeson "0.9.0.1"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_aeson */

/* package containers-0.5.6.3 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.6.3"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 6)
#endif /* MIN_VERSION_containers */

/* package ghcjs-base-0.2.0.0 */
#ifndef VERSION_ghcjs_base
#define VERSION_ghcjs_base "0.2.0.0"
#endif /* VERSION_ghcjs_base */
#ifndef MIN_VERSION_ghcjs_base
#define MIN_VERSION_ghcjs_base(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_ghcjs_base */

/* package servant-0.11 */
#ifndef VERSION_servant
#define VERSION_servant "0.11"
#endif /* VERSION_servant */
#ifndef MIN_VERSION_servant
#define MIN_VERSION_servant(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 0)
#endif /* MIN_VERSION_servant */

/* package network-uri-2.6.1.0 */
#ifndef VERSION_network_uri
#define VERSION_network_uri "2.6.1.0"
#endif /* VERSION_network_uri */
#ifndef MIN_VERSION_network_uri
#define MIN_VERSION_network_uri(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_network_uri */

/* tool alex-3.2.4 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.4"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */

/* tool cpphs-1.20.8 */
#ifndef TOOL_VERSION_cpphs
#define TOOL_VERSION_cpphs "1.20.8"
#endif /* TOOL_VERSION_cpphs */
#ifndef MIN_TOOL_VERSION_cpphs
#define MIN_TOOL_VERSION_cpphs(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_cpphs */

/* tool gcc-6.4.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "6.4.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  6 || \
  (major1) == 6 && (major2) <  4 || \
  (major1) == 6 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-7.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "7.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-7.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "7.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool ghcjs-0.2.0 */
#ifndef TOOL_VERSION_ghcjs
#define TOOL_VERSION_ghcjs "0.2.0"
#endif /* TOOL_VERSION_ghcjs */
#ifndef MIN_TOOL_VERSION_ghcjs
#define MIN_TOOL_VERSION_ghcjs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_ghcjs */

/* tool ghcjs-pkg-7.10.3 */
#ifndef TOOL_VERSION_ghcjs_pkg
#define TOOL_VERSION_ghcjs_pkg "7.10.3"
#endif /* TOOL_VERSION_ghcjs_pkg */
#ifndef MIN_TOOL_VERSION_ghcjs_pkg
#define MIN_TOOL_VERSION_ghcjs_pkg(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghcjs_pkg */

/* tool haddock-2.16.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.16.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  16 || \
  (major1) == 2 && (major2) == 16 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool happy-1.19.9 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.19.9"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  19 || \
  (major1) == 1 && (major2) == 19 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_happy */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.67 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.67"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */

/* tool pkg-config-1.5.3 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.5.3"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-7.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "7.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  10 || \
  (major1) == 7 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.28 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.28"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  28 || \
  (major1) == 2 && (major2) == 28 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "app-0.1.0.0-Li0Gi2dxg3t5IbJ1j7d2RE-app"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */
